from datetime import datetime, timezone
from pathlib import Path

from backend.policies.event_log import record_policy_hit_events
from backend.repositories.analysis_repo import AnalysisRepository
from backend.workflow.state import EmailAnalysisState



def make_persist_analysis_node(analysis_repo: AnalysisRepository, session_factory, report_store):
    def persist_analysis(state: EmailAnalysisState):
        report_payload = state.get("report", {}) or {}
        report_markdown = str(report_payload.get("markdown") or "")
        report_path = report_store.write_report(state["analysis_id"], report_markdown)

        parsed_email = state.get("parsed_email", {}) or {}
        payload = {
            "id": state["analysis_id"],
            "message_id": parsed_email.get("message_id") or state.get("message_id") or None,
            "fingerprint": state["email_fingerprint"],
            "sender": parsed_email.get("sender", ""),
            "recipient": parsed_email.get("recipient", ""),
            "subject": parsed_email.get("subject", ""),
            "parsed_email": parsed_email,
            "url_extraction": state.get("url_extraction", {}),
            "url_reputation": state.get("url_reputation", {}),
            "url_analysis": state.get("url_analysis", {}),
            "content_review": state.get("content_review", {}),
            "attachment_analysis": state.get("attachment_analysis", {}),
            "decision": state.get("decision", {}),
            "report_markdown": report_markdown,
            "report_path": str(report_path),
            "execution_trace": state.get("execution_trace", []),
            "created_at": datetime.now(timezone.utc),
        }

        with session_factory() as db:
            saved = analysis_repo.create(db, payload)
            record_policy_hit_events(db, analysis_id=saved.id, policy_evaluation={})
            db.commit()
            saved_id = saved.id
            saved_report_path = str(saved.report_path)
            saved_created_at = saved.created_at or payload["created_at"]

        final_report_path = saved_report_path
        if final_report_path != str(report_path):
            # Duplicate insert race: cleanup orphan report generated by this attempt.
            try:
                Path(report_path).unlink(missing_ok=True)
            except Exception:
                pass

        return {
            "analysis_id": saved_id,
            "report_path": final_report_path,
            "report": {
                "markdown": report_markdown,
                "summary": str(report_payload.get("summary") or ""),
                "path": final_report_path,
            },
            "created_at": saved_created_at.isoformat(),
            "execution_trace": state["execution_trace"] + ["persist_analysis"],
        }

    return persist_analysis
