from datetime import datetime, timezone
from pathlib import Path

from backend.repositories.analysis_repo import AnalysisRepository
from backend.workflow.state import EmailAnalysisState



def make_persist_analysis_node(analysis_repo: AnalysisRepository, session_factory, report_store):
    def persist_analysis(state: EmailAnalysisState):
        report_path = report_store.write_report(state["analysis_id"], state.get("llm_report", ""))

        payload = {
            "id": state["analysis_id"],
            "message_id": state.get("message_id") or None,
            "fingerprint": state["email_fingerprint"],
            "sender": state.get("sender", ""),
            "recipient": state.get("recipient", ""),
            "subject": state.get("subject", ""),
            "url_analysis": state.get("url_analysis", {}),
            "body_analysis": state.get("body_analysis", {}),
            "attachment_analysis": state.get("attachment_analysis", {}),
            "final_decision": state.get("final_decision", {}),
            "llm_report": state.get("llm_report", ""),
            "report_path": str(report_path),
            "execution_trace": state.get("execution_trace", []),
            "created_at": datetime.now(timezone.utc),
        }

        with session_factory() as db:
            saved = analysis_repo.create(db, payload)

        final_report_path = str(saved.report_path)
        if final_report_path != str(report_path):
            # Duplicate insert race: cleanup orphan report generated by this attempt.
            try:
                Path(report_path).unlink(missing_ok=True)
            except Exception:
                pass

        return {
            "analysis_id": saved.id,
            "report_path": final_report_path,
            "created_at": (saved.created_at or payload["created_at"]).isoformat(),
            "execution_trace": state["execution_trace"] + ["persist_analysis"],
        }

    return persist_analysis
